r"""Render a :class:`PersonaSourceIndex` to deterministic markdown + JSON.

Determinism:

* ``render_json`` emits ``json.dumps(..., sort_keys=True,
  ensure_ascii=False, indent=2)`` plus a single trailing ``\\n``.
* ``render_markdown`` walks sources / habit buckets in ``source_key``
  order with a fixed layout and a single trailing ``\\n``.

Neither carries a wall-clock timestamp, so the artefacts are byte-stable
across runs at the same input state and ``--check`` can compare bytes.

No LLM / summariser is involved: the prose is a template over verbatim
model fields. The header states plainly that citations are
maintainer-entered (unverified) and that ``bibliographic_only`` sources
have **no committed document body** — a citation is not evidence.
"""

from __future__ import annotations

import json

from erre_sandbox.evidence.source_navigator.models import (
    PersonaSourceIndex,
    SourceAvailability,
)

_GENERATED_BANNER: str = (
    "<!-- GENERATED by erre-sandbox source-index. DO NOT EDIT BY HAND. "
    "Regenerate with: python -m erre_sandbox source-index --persona <id>. -->"
)


def render_json(index: PersonaSourceIndex) -> str:
    """Return the canonical JSON serialisation (trailing newline included)."""
    payload = index.model_dump(mode="json")
    return json.dumps(payload, sort_keys=True, ensure_ascii=False, indent=2) + "\n"


def _availability_label(node_availability: SourceAvailability) -> str:
    if node_availability is SourceAvailability.BIBLIOGRAPHIC_ONLY:
        return "bibliographic_only (citation registered; NO committed document body)"
    return "body_present (committed document body)"


def render_markdown(index: PersonaSourceIndex) -> str:
    """Return the deterministic INDEX.md text (trailing newline included)."""
    lines: list[str] = [
        _GENERATED_BANNER,
        "",
        f"# Source Navigator — {index.persona_id}",
        "",
        f"- schema_version: `{index.schema_version}`",
        f"- generated_by: `{index.generated_by}`",
        f"- source_digest: `{index.source_digest}`",
        "",
        "> **Evidence discipline.** A citation is **not** evidence. Sources marked",
        "> `bibliographic_only` have no committed document body in this repo; their",
        "> citation metadata is maintainer-entered and **not auto-verified**",
        "> (`metadata_verified: false`). Do not treat a citation — or any summary —",
        "> as substantiation of the habit text.",
        "",
        "## Sources (depth 1)",
        "",
    ]

    for node in sorted(index.sources, key=lambda n: n.source_key):
        citation = node.citation
        year = citation.year if citation.year is not None else "n.d."
        lines.append(f"### `{node.source_key}` — {citation.author} ({year})")
        lines.append("")
        lines.append(f"- title: *{citation.title}*")
        lines.append(f"- availability: {_availability_label(node.availability)}")
        lines.append(f"- body_absent_reason: `{citation.body_absent_reason}`")
        lines.append(
            f"- work_pd_by_age: `{str(citation.work_pd_by_age).lower()}`"
            f" (basis: {citation.pd_basis})",
        )
        lines.append(
            f"- body_committable: `{str(citation.body_committable).lower()}`",
        )
        lines.append(
            f"- metadata_verified: `{str(citation.metadata_verified).lower()}`"
        )
        if node.body is not None:
            lines.append(f"- document_id: `{node.body.document_id}`")
        lines.append("")
        lines.append(f"#### Habits citing `{node.source_key}` (depth 2)")
        lines.append("")
        for habit in index.habits_by_source[node.source_key]:
            zone = habit.trigger_zone.value if habit.trigger_zone is not None else "—"
            lines.append(f"- **[{habit.flag.value}]** {habit.description}")
            lines.append(f"  - trigger_zone: `{zone}`")
            lines.append(f"  - mechanism: {habit.mechanism}")
        lines.append("")

    return "\n".join(lines).rstrip("\n") + "\n"


__all__ = ["render_json", "render_markdown"]
